= Analyse du domaine
 
== Introduction

Risk est un jeu de conquete du monde, pour deux a six joueurs, chaque joueur doit  lancer les dés(3 dés de couleur rouge pour attaquer et de dés de couleur  blanche pour defendre)  pour gagner les batailles avec ses troupes et échanger des cartes territoires  pour obtenir des renforts.Il s'agit ici de compter sur ses tactiles
afin de de mener ses troupes vers la victoire en prenant d'abord le controle des territoires, puis des continents entiers pour la
domination du monde.  
D’un point de vue fonctionnel, Risk a deux cas d’utilisation (ou fonctionnalités) principaux: la mise en place d’un jeu et jouer un tour. 



== Cas d'utilisation principaux

Dans cette section, nous utilisons les Cas d’utilisation efficaces d’Alistar Cockburn pour spécifier les cas d’utilisation principaux de Risk:

1. mise en place du jeu .
2. Jouer un tour.

== Acteurs

Nous avons considéré deux acteurs, le joueur et l'arbitre qui va reguler le jeu.

=== Joueur
Le joueur est celui qui joue une partie. La partie comprend deux a six joueurs, qui sont des adversaires, l’un de l’autre.
Un seul des joueurs commence la partie, l'initiateur.

=== Arbitre
L’arbitre veille au bon déroulement des parties. Il calcule les effets à appliquer en début et fin de tour.

=== Use case 1: Initilisation du Jeu
==== Description 
L'initilisation du Jeu consiste à mélanger les cartes territoire  (y comprir les 2 jokers) et les placer en pile, face caché. C'est la pioche.
Chaque joueur choisit une couleur parmir les couleurs (rouge,jaune,rose,noir,bleu ,vert)et prends  les pions de cette couleur, ils représentent son armée. Le nombre de
régiments de départ dépend du nombre de joueurs:

* A 3 joueurs chacun prend 35 armées
* A 4 joueurs chacun prend 30 armées
* A 5 joueurs chacun prend 25 armées
* A 6 joueurs chacun prend 20 armées

Les régiments de départ seront placés sur le plateau de jeu avant de commencer la partie.
Chaque joueur lance un dé pour déterminer le premier joueur. Celui qui obtient le résultat
le plus haut commence (en cas d'égalité,il faut lancer à nouveau). suivi du joueur situé à sa gauche.


==== Acteurs principaux

1. Les joueurs

2. L’arbitre

==== Acteurs de soutien
Aucun pour l’instant

==== Parties prenantes et intérêt
Aucun pour l’instant


==== Pré-conditions
Le contenu du jeu doit etre complet:

* Le plateau de jeu.
* 3 dés rouges et 2 dés bleu.
* Des pions de 6 couleurs differentes representant les armées.
* Les armées(55 exemplaires correspondant à 1 armée, 9 exemplaires correspondant à 5 armées et 7 exemplaires correspondant à 10 armées).
* 42 cartes territoires repartis sur les continents comme suite:

1. Afrique de couleur marron avec 6 territoire.
2. Asie de couleur verte avec 12 territores.
3. Océanie de couleur grise avec 4 territoire.
4. Europe de couleur bleu avec 7 territoires.
5. Amérique du nord de couleur jaune avec 9 territoires.
6. Amérique du Sud de couleur orange avec 4 territoires.
* 28 cartes Mission.
* 2 cartes jokers.

L’arbitre et les joueurs doivent etre disponible.

==== Post-conditions
===== Condition finale de réussite
Chaque joueur recoit ses cartes mission .
Chaque joueur recoit le nombre d'armées en fonction  du nombre  joueurs.
Les régiment de départ placés sur le plateau de jeu.

===== Condition finale d’échec
Les joueurs n’ont pas reçu leurs cartes 
Le partage des armées ne s'est pas fait en fonction des joueurs.

===== Garanties minimales
Aucune

===== Événement déclencheur

Les deux joueurs se retrouvent et souhaitent s’affronter.

== Conclusion

